// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndPomodoro(arg1) {
  return window['go']['api']['PomodoroAPI']['EndPomodoro'](arg1);
}

export function GetActivePomodoro() {
  return window['go']['api']['PomodoroAPI']['GetActivePomodoro']();
}

export function StartPomodoro(arg1, arg2) {
  return window['go']['api']['PomodoroAPI']['StartPomodoro'](arg1, arg2);
}

export function SwitchToBreak(arg1) {
  return window['go']['api']['PomodoroAPI']['SwitchToBreak'](arg1);
}
