// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function EndPomodoro(arg1:number):Promise<domain.PomodoroSession>;

export function GetActivePomodoro():Promise<domain.PomodoroSession>;

export function StartPomodoro(arg1:number,arg2:number):Promise<domain.PomodoroSession>;

export function SwitchToBreak(arg1:number):Promise<domain.PomodoroSession>;
